remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have onetheme: jekyll-theme-cayman
title: Életciklus blog
description: A környezeti lábnyomunkról közérthetően
excerpt_separator: <!--more-->
